# Generated by Django 5.2.17 on 2026-10-02 07:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Official three-digit Kenya county code.', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('has_nasa_power_coverage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='county_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), _connector='OR'), name='county_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), _connector='OR'), name='county_longitude_range')],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('precipitation_max_mm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('temperature_mean_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('relative_humidity_mean_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('soil_wetness_mean_fraction', models.DecimalField(decimal_places=6, max_digits=8)),
                ('soil_wetness_max_fraction', models.DecimalField(decimal_places=6, max_digits=8)),
                ('month_sin', models.DecimalField(decimal_places=8, max_digits=10)),
                ('month_cos', models.DecimalField(decimal_places=8, max_digits=10)),
                ('source', models.CharField(choices=[('NASA_POWER', 'NASA POWER'), ('IMPORTED', 'Imported historical data'), ('MANUAL', 'Manual entry')], default='NASA_POWER', max_length=20)),
                ('source_record_id', models.CharField(blank=True, default='', max_length=150)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('quality_review_required', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_observations', to='monitoring.county')),
            ],
            options={
                'ordering': ['-observation_date', 'county__name'],
            },
        ),
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('probability_low', models.DecimalField(decimal_places=6, max_digits=7)),
                ('probability_medium', models.DecimalField(decimal_places=6, max_digits=7)),
                ('probability_high', models.DecimalField(decimal_places=6, max_digits=7)),
                ('model_release_id', models.CharField(max_length=100)),
                ('decision_rule', models.CharField(max_length=100)),
                ('high_probability_threshold', models.DecimalField(decimal_places=6, default=Decimal('0.440000'), max_digits=7)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='monitoring.environmentalobservation')),
            ],
            options={
                'ordering': ['-observation__observation_date', 'observation__county__name'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], default='IN_APP', max_length=20)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='monitoring.floodprediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='environmentalobservation',
            index=models.Index(fields=['observation_date'], name='observation_date_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalobservation',
            index=models.Index(fields=['source'], name='observation_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.UniqueConstraint(fields=('county', 'observation_date'), name='unique_county_observation_date'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('precipitation_max_mm__gte', Decimal('0'))), name='observation_precipitation_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('temperature_mean_c__gte', Decimal('-100')), ('temperature_mean_c__lte', Decimal('100'))), name='observation_temperature_range'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('relative_humidity_mean_pct__gte', Decimal('0')), ('relative_humidity_mean_pct__lte', Decimal('100'))), name='observation_humidity_range'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('soil_wetness_mean_fraction__gte', Decimal('0')), ('soil_wetness_mean_fraction__lte', Decimal('1'))), name='observation_soil_mean_range'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('soil_wetness_max_fraction__gte', Decimal('0')), ('soil_wetness_max_fraction__lte', Decimal('1'))), name='observation_soil_max_range'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('soil_wetness_max_fraction__gte', models.F('soil_wetness_mean_fraction'))), name='observation_soil_max_gte_mean'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('month_sin__gte', Decimal('-1')), ('month_sin__lte', Decimal('1'))), name='observation_month_sin_range'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('month_cos__gte', Decimal('-1')), ('month_cos__lte', Decimal('1'))), name='observation_month_cos_range'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['risk_level', 'predicted_at'], name='prediction_risk_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='floodprediction',
            constraint=models.UniqueConstraint(fields=('observation', 'model_release_id'), name='unique_observation_model_release'),
        ),
        migrations.AddConstraint(
            model_name='floodprediction',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__in', ['Low', 'Medium', 'High'])), name='prediction_risk_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='floodprediction',
            constraint=models.CheckConstraint(condition=models.Q(('probability_low__gte', Decimal('0')), ('probability_low__lte', Decimal('1'))), name='prediction_low_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='floodprediction',
            constraint=models.CheckConstraint(condition=models.Q(('probability_medium__gte', Decimal('0')), ('probability_medium__lte', Decimal('1'))), name='prediction_medium_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='floodprediction',
            constraint=models.CheckConstraint(condition=models.Q(('probability_high__gte', Decimal('0')), ('probability_high__lte', Decimal('1'))), name='prediction_high_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='floodprediction',
            constraint=models.CheckConstraint(condition=models.Q(('high_probability_threshold__gte', Decimal('0')), ('high_probability_threshold__lte', Decimal('1'))), name='prediction_high_threshold_range'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status', 'created_at'], name='alert_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertnotification',
            constraint=models.UniqueConstraint(fields=('prediction', 'channel', 'recipient'), name='unique_prediction_alert_recipient'),
        ),
        migrations.AddConstraint(
            model_name='alertnotification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SENT'), _negated=True), ('sent_at__isnull', False), _connector='OR'), name='sent_alert_requires_timestamp'),
        ),
    ]
